koudelka/honeydew

- README.md
- lib/honeydew.ex
- lib/honeydew/failure_mode/abandon.ex
- lib/honeydew/failure_mode/requeue.ex
- lib/honeydew/monitor.ex
- lib/honeydew/queue.ex
- lib/honeydew/worker.ex
- mix.exs
- mix.lock
- test/honeydew/queue_supervisor_test.exs
- test/honeydew_test.exs
I started a dummy project this morning to evaluate honeydew and noticed there was also a GenStage update today that removed the `Experimental` namespace (see [CHANGELOG.md#v0110](https://github.com/elixir-lang/gen_stage/blob/master/CHANGELOG.md#v0110)) which prevented me from from getting it running.
**Changes Made**
- removed all `Experimental` aliases for GenStage from modules
- removed all full namespace references in tests with `Experimental` prefixes for GenStage
- fixed URLs to GenStage documentation in README
**Not Done**
- `test/honeydew/queue/erlang_queue_integration_test.exs:41` is failing, but does not appear to be related to these changes. I will pull another version and pin GenStage to v0.10.0 to verify
- I did not mess with your version number or anything in the mix.exs file …
> GenStage 0.11.0 release

- lib/honeydew.ex
- test/honeydew_test.exs
This allows passing options to `Supervisor.Spec.supervisor/3` when defining queue and worker supervisors with `queue_spec/2` and `worker_spec/2`.
A use case of when it's needed is specifying supervisor ids when defining multiple queues in the same application like this:
```elixir
defmodule QueueApp do
def start do
nodes = [node()]
children = [
Honeydew.queue_spec({:global, :first_queue}, queue: {Honeydew.Queue.Mnesia, [nodes, [disc_copies: nodes], []]}),
Honeydew.queue_spec({:global, :second_queue}, queue: {Honeydew.Queue.Mnesia, [nodes, [disc_copies: nodes], []]}),
]
Supervisor.start_link(children, strategy: :one_for_one)
end
end
QueueApp.start
```
which currently fails with:
```
** (ArgumentError) duplicated id Honeydew.QueueSupervisor found in the supervisor specification, please …
```
> Pass supervisor opts

- lib/honeydew/success_mode/log.ex
TravisCi is reporting the following compilation warnings when compiling the app in the test environment.
```
warning: the result of the expression is ignored (suppress the warning
by assigning the expression to the _ variable)
lib/honeydew/success_mode/log.ex:7
warning: the result of the expression is ignored (suppress the warning
by assigning the expression to the _ variable)
lib/honeydew/success_mode/log.ex:8
```
This is because we are purging all log statements lower than warning in the test environment.
```elixir
config :logger
compile_time_purge_level: :warn
```
This change puts both the calculations and text for the log message into a function so they can all be purged together and not cause compilation warnings.
> Fix compilation warnings

- .travis.yml
- mix.exs
This relaxes the mix.exs constraint to allow for elixir 1.4 and 1.5. It also tests against Elixir 1.4.5, 1.5.1 and OTP 19.1, 19.3, 20.0.
> Support for elixir 1.5

- lib/honeydew.ex
`Honeydew.queue_spec` and `Honeydew.worker_spec` have some formatting issues when viewing the docs. This makes the examples bulleted lists (so they aren't all on one line) and removes a stray backquote.
> Fix formatting in worker_spec and queue_spec docs

- README.md
- examples/distributed.exs
- examples/riak.exs
- examples/simple.exs
- lib/honeydew.ex
- lib/honeydew/worker.ex
- test/test_helper.exs
This adds a Honeydew.Worker behaviour which defines an optional init/1 callback. This helps the user to find out if they are returning an invalid value from the init/1 callback.
I also updated the Honeydew.worker_spec documentation to include default values and improve formatting.
> Add Honeydew.Worker behaviour

- lib/honeydew.ex
Since `Honeydew.worker_spec/3` passes the args from the `module_and_args` param directly to the Honeydew.Worker.init/1 callback, there is no reason why the arguments here have to be a list. After double-checking the args param for `GenServer.start_link/3` and the associated
`GenServer.init/1` callback, it appears common for the `args` param to be a term instead of a list.
> Update typespec so args is a term instead of list

- lib/honeydew.ex
- lib/honeydew/queue.ex
- lib/honeydew/queue/erlang_queue.ex
- lib/honeydew/queue/mnesia.ex
I was setting up a new queue, and found the docs could use a little more info. This adds a high level explanation for each queue module, as well as referencing the default `ErlangQueue` from `Honeydew.queue_spec/2`.
> Add basic queue docs

- README.md
Because the more badges you have, the cooler your project is. 😎 
But seriously, it would be nice to pull up the readme and see the current version without having to scroll.
> Add version badge to Readme

- test/honeydew/failure_mode/move_test.exs
- test/honeydew/failure_mode/retry_test.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
Since we are only using capture_log to silence the error output in the tests, it seems like it is less intrusive to use the `:capture_log` tag instead of wrapping everything in a function call. If a test fails
that's tagged with `:capture_log`, it will automatically dump all log output to the console.
> Prefer :capture_log tag when log data not tested

- lib/honeydew/queue.ex
- test/honeydew/queue/erlang_queue_integration_test.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
There is an issue where if new workers were added to a queue, they would start processing jobs, even if the queue is suspended. This moves the suspended check from Queue.enqueue to Queue.dispatch, giving us a single place to handle suspended queues.
While I was in there, I removed commented-out calls to non-existent resume and suspend functions.
> New workers shouldn't get jobs from suspended queues

- lib/honeydew.ex
- lib/honeydew/job.ex
- lib/honeydew/queue.ex
- test/honeydew/queue/erlang_queue_integration_test.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
This adds documentation and typespecs for the following functions:
* `Honeydew.filter/2`
* `Honeydew.async/3`
* `Honeydew.yield/2`
It also adds a `Honeydew.Job.t` type and starts filling in the types for the various fields on that struct. Finally, this fixes the typespec on the `Honeydew.Queue.filter/2` callback. The previous callback said that `filter/2` should return a non-empty list, which is not required.
> Add docs for async, yield, and filter

- lib/honeydew.ex
- lib/honeydew/queue.ex
- lib/honeydew/queue/erlang_queue.ex
- lib/honeydew/queue/mnesia.ex
- test/honeydew/queue/erlang_queue_integration_test.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
This documents `Honeydew.cancel/1` and adds typespecs for `cancel/1` in the two queue implementations.
> Documentation for cancel/1

- lib/honeydew.ex
- lib/honeydew/queue.ex
- lib/honeydew/queue_supervisor.ex
- test/honeydew/queue/erlang_queue_integration_test.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
- test/honeydew/queue_supervisor_test.exs
- test/honeydew_test.exs
This allows starting a queue in the suspended state.
> Start queue suspended

- lib/honeydew.ex
- test/honeydew/queue/erlang_queue_integration_test.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
This allows for moving the job from one queue to another.
> Add Honeydew.move/2

- lib/honeydew.ex
- test/honeydew/queue/erlang_queue_integration_test.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
- test/test_helper.exs
Looks like Honeydew.yield/2 returns `{:ok, result}` instead of just result. This fixes the docs and adds some test coverage.
> Fix Honeydew.yield/2 typespec

- README.md
Just updates an out of date link.
> Fix link to Task docs in README

- test/honeydew/failure_mode/abandon_test.exs
- test/honeydew/failure_mode/move_test.exs
- test/honeydew/failure_mode/retry_test.exs
This documents how Honeydew.yield returns failures when the job throws an uncaught value.
> Add tests for Honeydew.yield when job fails with uncaught throw

- lib/honeydew/crash.ex
- lib/honeydew/job_monitor.ex
- lib/honeydew/logger.ex
- lib/honeydew/logger/metadata.ex
- lib/honeydew/worker.ex
- mix.exs
- test/honeydew/logger/metadata_test.exs
- test/honeydew/logger_test.exs
- test/honeydew/worker_test.exs
- test/support/crash_logger_helpers.ex
This PR adds `:honeydew_crash_reason` messages to any job or worker init log messages for the purposes of allowing an error logging integration to be built. This would allow an error logger to be build like this
```elixir
defmodule MyApp.LoggerBackend do
@moduledoc false
@behaviour :gen_event
def init(arg) do
{:ok, %{}}
end
def handle_call({:configure, _options}, state), do: {:ok, :ok, state}
def handle_event({_level, _pid, {Logger, msg, _timestamp, metadata}} = event, state) do
case Keyword.fetch(metadata, :honeydew_crash_reason) do
{:ok, crash_reason} ->
report_error(crash_reason)
{:ok, state}
:error ->
{:ok, state}
end
end
def handle_event(_, state) do
{:ok, state}
end
def code_change(_old_vsn, state, _extra) do
{:ok, state}
end
defp report_error({%{__struct__: _} = exception, …
```
> Log metadata on Worker.init or Job.run crashes

- lib/honeydew/job_runner.ex
- lib/honeydew/worker.ex
- test/hammer/hammer.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
- test/honeydew_test.exs
- test/support/workers/failed_init_worker.ex
it occurs to me that if we truly want to assume chaos in user job code, it has to be as isolated as possible. so this change moves actual job execution out of the Worker and into one-time-use processes (`JobRunner`s) that the Worker spawns. the Worker is still responsible for everything else (holding immutable state from job module init, reporting success/failure, etc)
previously, jobs were able to write to the process dictionary of the worker, link to arbitrary processes and other horrible things. they're still welcome to do that, it's just that the process that it mutilated will now die immediately after the job has finished.
> don't run jobs in the Worker, run them in a one-time-use processes.

- .travis.yml
- examples/ecto_poll_queue/mix.cockroach.lock
- examples/ecto_poll_queue/mix.exs
- examples/ecto_poll_queue/mix.postgres.lock
- test/honeydew/queue/ecto_poll_queue_integration_test.exs
I saw all of the places where you had to delete the`mix.lock` file for the ecto poll queue, and thought what if there were separate lock files per env? This may not be what you want, but I thought I'd just share the idea.
> Add lock file per env for examples/ecto_poll_queue

- .gitignore
- .tool-versions
- README.md
- README/queues.md
- examples/delayed_job.exs
- examples/ecto_poll_queue/lib/ecto_poll_queue_example/application.ex
- examples/ecto_poll_queue/test/ecto_poll_queue_example_test.exs
- examples/exponential_retry.exs
- examples/filter_and_cancel.exs
- examples/mnesia.exs
- lib/honeydew.ex
- lib/honeydew/failure_mode/exponential_retry.ex
- lib/honeydew/failure_mode/retry.ex
- lib/honeydew/job.ex
- lib/honeydew/queue/erlang_queue.ex
- lib/honeydew/queue/mnesia.ex
- lib/honeydew/queue/mnesia/wrapped_job.ex
- lib/honeydew/queues.ex
- lib/honeydew/sources/ecto/sql.ex
- lib/honeydew/sources/ecto/sql/cockroach.ex
- lib/honeydew/sources/ecto/sql/postgres.ex
- lib/honeydew/sources/ecto/state.ex
- lib/honeydew/sources/ecto_source.ex
- test/hammer/hammer.exs
- test/honeydew/failure_mode/exponential_retry_test.exs
- test/honeydew/failure_mode/retry_test.exs
- test/honeydew/queue/erlang_queue_integration_test.exs
- test/honeydew/queue/mnesia_queue_integration_test.exs
- test/honeydew/queues_test.exs
this PR introduces the concept of time into honeydew's API, specifically:
- adds the `delay_secs: <integer>` argument to `async/3`
- adds the `ExponentialRetry` failure mode
- generalizes the `Retry` failure mode to accept a user function to indicate the delay between retries
- generalizes the way jobs are stored in the Mnesia queue to allow for new features
- adds examples and documentation
I've moved the default queue to an in-memory Mnesia store, it's about half the raw speed of ErlangQueue (at 16k jobs/sec), but it supports the delay api. 
i'll get around to writing a priority queue implementation at some point for ErlangQueue if folks end up needing that kind of speed (probably a https://en.wikipedia.org/wiki/Fibonacci_heap). 
ref: https://github.com/koudelka/honeydew/issues/66
> Delayed Jobs + Exponential Retry

- README.md
I was confused because the section on "strong job custody" says that "Jobs don't leave the queue until either they succeed, are explicitly abandoned or are moved to another queue." Yet I had failing jobs that did not get restarted, even though I had not explicitly abandoned them. It took me some time to track down this issue, so I thought it was worth mentioning here.
> Mention default failure mode

- lib/honeydew.ex
I was wondering about this - whether they'd be a bottleneck or not.
> they can also crash that process
Not sure what the implications of this would be.
> Note that handlers are run by monitor processes

- examples/ecto_poll_queue/README.md
This is just something I have missed twice now so I wanted to make it clear that the queue can be configured this way as well. And the `seconds` thing as we discussed on slack @koudelka.
Let me know if you want something else in here added as well.
> Add an extra example for queue arg configuration

- lib/honeydew/sources/ecto/sql.ex
I found warnings when I run `MIX_ENV=postgres mix ecto.migrate` in the the `ecto_poll_queue` example with Elixir 1.11.0:
```
warning: incompatible types:
map() !~ atom()
in expression:
sql_module.ready
where "sql_module" was given the type atom() (due to calling var.fun()) in:
sql_module.integer_type()
where "sql_module" was given the type map() (due to calling var.field) in:
sql_module.ready
HINT: "var.field" (without parentheses) implies "var" is a map() while "var.fun()" (with parentheses) implies "var" is an atom()
Conflict found at
priv/repo/migrations/20180408023001_create_photos_and_users.exs:20: EctoPollQueueExample.Repo.Migrations.CreatePhotosAndUsers.change/0
```
> Fix compile warnings on Elixir 1.11

- lib/honeydew/sources/ecto/sql/postgres.ex
In default postgresql will cast to `INTEGER`, prevent overflow via manual cast to `BIGINT`
> prevent 'integer out of range' error in delay_ready

- lib/honeydew.ex
See #105 
https://github.com/koudelka/honeydew/blob/1b07343e0d1df2b2819ca050b3d12c66d8b54cf0/lib/honeydew/queues.ex#L30-L36
The default queue is `Honeydew.Queue.Mnesia`.
> Fix documentation on the default queue for `start_queue`
